model_params: 
  model_name: 'vae_ia_att'
  backbone_name: 'Residual_VAEGAN'
  in_channels: 3
  latent_dim: 512
  recon_level: 2
  img_size: 128
  ckpt: 'best.ckpt'
  backbone_1:
    name: 'Residual_VAEGAN'
    in_channels: 3
    latent_dim: 512
    recon_level: 2
    img_size: 128
    ckpt: False
  backbone_2:
    name: 'Residual_VAEGAN'
    in_channels: 1
    latent_dim: 512
    recon_level: 2
    img_size: 128
    ckpt: False
  classifier:
    ckpt: False

data_params:
  data_path: "/shared/datasets/CA_FER/RAVDESS_CROPP_VA"
  data_file: fold_1.yaml
  train_batch_size: 128
  val_batch_size:  64
  test_batch_size: 64
  patch_size: 128
  num_workers: 4
  mean: False
  std: False
  crop: 322
  feature:
    type: Mel_frequence
    sr: 22050
    n_fft: 1310
    n_mels: 128
    n_mfcc: 64
    to_DB: True


exp_params:
  LR: 3e-4
  lambda_mse: 1
  decay_lr: 0.75
  decay_mse: 1
  decay_margin: 1
  decay_equilibrium: 1
  manual_seed: 999
  find_unused_parameters: True
  save_top_k: 5
  monitor: val_acc
  mode: max
  kld_weight: 0.00045
  num_classes: 7
  context: ia
  final_dim: 512
  kldloss_weight: 0.00001

trainer_params:
  gpus: [0]
  max_epochs: 30

logging_params:
  save_dir: "logs/"
  name: 'vae_ia'