model_params:
  backbone_name: 'Residual_VAEGAN'
  model_name: 'Residual_VAEGAN'
  in_channels: 3
  latent_dim: 512
  recon_level: 2
  img_size: 128
  ckpt: False
data_params:
  data_path: "RAVDESS_CROPP_VA"
  data_file: split_datas.yaml
  train_batch_size: 128
  val_batch_size:  64
  test_batch_size: 64
  patch_size: 128
  num_workers: 4
  mean: False
  std: False
  crop: 322
  feature:
    type: Mel_frequence
    sr: 22050
    n_fft: 1310
    n_mels: 128
    n_mfcc: 64
    to_DB: True
    augumentation: False


exp_params:
  LR: 3e-4
  lambda_mse: 1
  decay_lr: 0.75
  decay_mse: 1
  decay_margin: 1
  decay_equilibrium: 1
  manual_seed: 999
  find_unused_parameters: True
  save_top_k: 3
  monitor: val_loss_rec
  kld_weight: 0.00033
  mode: min

trainer_params:
  gpus: [0]
  max_epochs: 500

logging_params:
  save_dir: "logs/"
  name: 'Residual_VAEGAN'
